[project]
name = "iamspy"
version = "0.1.0"
description = ""
authors = [{ name = "Mohit Gupta", email = "mohit.gupta@reversec.com" }]
requires-python = ">=3.9,<4"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "z3-solver",
    "pydantic>=1,<2",
    "typer",
    "python-dateutil>=2.8.2,<3",
]

[project.scripts]
iamspy = "iamspy.cli:app"

[dependency-groups]
dev = [
    "ipython",
    "black",
    "pytest",
    "pytest-cov",
    "pdbpp",
    "setuptools",
]

[tool.uv]

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.10.4,<0.11.0"]
build-backend = "uv_build"

[tool.black]
line-length = 120
